name: zChat
description: A minimal chat plugin.
version: ${version}
main: dev.mrzcookie.zchat.ZChatPlugin
authors: [ MrZCookie, KaspianDev ]
api-version: 1.13
depend: [ LuckPerms ]
softdepend: [ PlaceholderAPI ]
